name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd5479a8a184b0fd369df7b85fc89d7fdf0452dc9cbbc5a071989344d842c518"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
