name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8ecd6689fbf87e62893802c3aff2bd8889c3d30e9f720113e55f19b16b0911f4"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
