name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dfc39d269abdaae76324505da1b308bb8b1b3924d02daac0fa51bbe92da4ef40"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
