name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8dc7a30af478a6f9e0f3f431471c3c4fa10618180b278d03762658d2f8699846"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
