name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63ac066925be7f83238c002fbd9cb2dcb983ff48de19bf1c9a2bc1fdd813ebde"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
