name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7d9829d5e9915eca6bf171e3de5a7ed9f05ee2636d151d0c4d26eb7d978e83fe"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
