name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "911af010040a58aa3b7e6b27f64b493593aca9e1ad40931b1a1427ad4f057692"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
