name = "SteamDeck"
author = "Merith-TK"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "487b5441140801149b75b0ac41eec0a768ca4b633dfd3a2572666614ea8aaa1c"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
